name: hookah_search
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_phone_direct_caller: ^2.1.1
  flutter_rating_bar: ^4.0.1
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.9
  hexcolor: ^2.0.7
  page_transition: ^2.0.9
  rxdart: ^0.27.5
  sizer: ^2.0.15
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: PTMono
      fonts:
        - asset: assets/fonts/PTMono-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoHS2.png"
